# recipe https://www.recipetineats.com/honey-garlic-chicken/
print("1 Serving consists of:")
print("1/16 cup Flower")
print("7/8 tbsp Unsalted Butter")
print("0.5 Garlic Cloves")
print("3/8 tbsp Apple Cider Vinegar")
print("1/4 tbsp Soy Sauce")
print("1/12 cup Honey")
NUM_SERVINGS = input("How many servings do you need?:\n")
print("You will need the following ingredients:")
NUM_SERVINGS = float(NUM_SERVINGS)
SUM_INGREDIENT = format((1/2)*NUM_SERVINGS, '.2f')
print(SUM_INGREDIENT, "Chicken Breasts")
SUM_INGREDIENT = format((1/16)*NUM_SERVINGS, '.2f')
print(SUM_INGREDIENT, "cups Flour")
SUM_INGREDIENT = format((7/8)*NUM_SERVINGS, '.2f')
print(SUM_INGREDIENT, "tbsp Unsalted Butter")
SUM_INGREDIENT = format(0.5*NUM_SERVINGS, '.2f')
print(SUM_INGREDIENT, "Garlic Cloves")
SUM_INGREDIENT = format((3/8)*NUM_SERVINGS, '.2f')
print(SUM_INGREDIENT, "tbsp Apple Cider Vinegar")
SUM_INGREDIENT = format((1/4)*NUM_SERVINGS, '.2f')
print(SUM_INGREDIENT, "tbsp Soy Sauce")
SUM_INGREDIENT = format((1/12)*NUM_SERVINGS, '.2f')
print(SUM_INGREDIENT, "cups Honey")
