noun2 = input("Enter a noun")
noun3 = input("Enter a noun:")
color = input("Enter a color:")
noun = input("Enter a noun:")
place = input("Enter the name of a place:")
verb = input("Enter the name of a verb:")
adjective = input("Enter a adjective:")
group = input("Enter the name of a group of people:")
time = input("Enter a unit of time(days/hours/seconds):")



print(" Poem Simplon Pass(Madlib), The by William Wordsworth \n")
print("------Brook and road ")
print("Were " + group + " in this gloomy Pass,")
print("And with them did we journey several" + time)
print("At a slow step. The immeasurable height")
print("Of woods decaying, never to be decayed,")
print("The stationary " + verb + " of waterfalls,")
print("And in the narrow rent, at every turn,")
print("Winds thwarting" + noun3 + "bewildered and forlorn,")
print("The torrents shooting from the" + place + ",")
print("The rocks that muttered close upon our ears,")
print(color + "drizzling crags that spake by the wayside")
print("As if a voice were in them, the sick sight")
print("And giddy prospect of the raving stream,")
print("The unfettered" + noun2 + "and region of the heavens,")
print("Tumult and peace, the darkness and the light--")
print("Were all like workings of one mind, the features")
print("Of the same face, blossoms upon one tree,")
print(noun + "of the great Apocalypse,")
print("The types and symbols of Eternity,")
print("Of first, and last, and midst, and without end.")
